import {Slide, Link, SocietySlide, MenuItem } from './types';

export const PRIVATE_SLIDER_ITEMS: Slide[] = [
  {
    title: 'PREMIUM PREMIUM PREMIUM PREMIUM PREMIUM PREMIUM PREMIUM PREMIUM PREMIUM PREMIUM PREMIUM PREMIUM PREMIUM PREMIUM PREMIUM ',
    subtitle: 'Расширенные возможности',
    note: 'Твой на\xA0все 365',
    text: 'Это выгодная подписка на\xA0сервисы экосистемы: музыка, онлайн кинотеатр Kion, 50 гб интернета, карта МТС банка с\xA0повышенным кешбэком, скидки на\xA0urent и\xA0belka car.',
    squarePicture: '../../assets/images/products/prods10.svg',
    backgroundImage: '',
    theme: null,
  },
  {
    title: 'JUNIOR JUNIOR JUNIOR JUNIOR JUNIOR JUNIOR JUNIOR JUNIOR JUNIOR JUNIOR JUNIOR JUNIOR JUNIOR JUNIOR JUNIOR JUNIOR ',
    subtitle: 'Для детей',
    note: 'Твой на\xA0все 365',
    text: 'Экосистемные сервисы МТС в\xA0выгодной и\xA0безопасной подписке для\xA0детей',
    squarePicture: '../../assets/images/products/prods12.svg',
    backgroundImage: '',
    theme: null,
  },
  {
    title: 'МУЗЫКА МУЗЫКА МУЗЫКА МУЗЫКА МУЗЫКА МУЗЫКА МУЗЫКА МУЗЫКА МУЗЫКА',
    subtitle: 'Качай и\xA0слушай',
    note: 'Твой на\xA0все 365',
    text: 'Музыка и\xA0ничего лишнего: удобное приложение для\xA0прослушивания музыки с\xA0большой коллекцией треков, классной рекомендательной системой и\xA0оффлайн режимом',
    squarePicture: '../../assets/images/products/prods01.svg',
    backgroundImage: '../../assets/images/products/products_mobile_04.svg',
    theme: {
      bgColor: '#C9E2C9',
    },
  },
  {
    title: 'KION KION KION KION KION KION KION KION KION KION KION KION KION KION KION KION KION KION KION KION',
    subtitle: 'Онлайн-кинотеатр',
    note: 'Твой на\xA0все 365',
    text: 'KION - онлайн кинотеатр с\xA0большой библиотекой фильмов и сериалов, а также собственная студия по\xA0производству Kion Originals — собственного эксклюзивного контента',
    squarePicture: '../../assets/images/products/prods03.svg',
    backgroundImage: '',
    theme: null,
  },
  {
    title: 'СТРОКИ СТРОКИ СТРОКИ СТРОКИ СТРОКИ СТРОКИ СТРОКИ СТРОКИ СТРОКИ СТРОКИ СТРОКИ СТРОКИ СТРОКИ СТРОКИ СТРОКИ СТРОКИ ',
    subtitle: 'Для читающих',
    note: 'Твоя на\xA0все 365',
    text: 'Строки — это современная онлайн платформа для\xA0непрерывного развития: книги и\xA0аудиокниги, последние новинки, эксклюзивы, лекции, подкасты на\xA0книжную тематику и\xA0электронные учебники',
    squarePicture: '../../assets/images/products/prods04.svg',
    backgroundImage: '../../assets/images/products/products_mobile_04.svg',
    theme: null,
  },
  {
    title: 'LIVE LIVE LIVE LIVE LIVE LIVE LIVE LIVE LIVE LIVE LIVE LIVE LIVE LIVE LIVE LIVE LIVE LIVE LIVE LIVE',
    subtitle: 'Культурные события',
    note: 'Твой на\xA0все 365',
    text: 'МТС Live культивирует эстетику и\xA0ценность культурной жизни. Вдохновляет на\xA0то, чтобы жить интересно и\xA0разнообразно, всегда находить время на\xA0себя и\xA0свои интересы',
    squarePicture: '../../assets/images/products/prods02.svg',
    backgroundImage: '',
    theme: {
      bgColor: '#333333',
      textColor: '#fff',
      titleColor: '#ffffff',
      paginationColor: '#fff',
    },
  },
  {
    title: 'ТЕЛЕКОМ ТЕЛЕКОМ ТЕЛЕКОМ ТЕЛЕКОМ ТЕЛЕКОМ ТЕЛЕКОМ ТЕЛЕКОМ ТЕЛЕКОМ ТЕЛЕКОМ ТЕЛЕКОМ ТЕЛЕКОМ ТЕЛЕКОМ ТЕЛЕКОМ ТЕЛЕКОМ ТЕЛЕКОМ ',
    subtitle: 'Интернет и\xA0связь',
    note: 'Твой на\xA0все 365',
    text: 'Лидирующие телеком продукты, гибкие настройки тарифа, прозрачная система контроля за\xA0расходами на\xA0мобильную и\xA0фиксированную связь, а также расширения стандартных тарифов.',
    squarePicture: '../../assets/images/products/prods09.svg',
    backgroundImage: '',
    theme: null,
  },
  {
    title: 'Exolve Exolve Exolve Exolve Exolve Exolve Exolve Exolve Exolve Exolve Exolve Exolve',
    subtitle: 'Умные технологии',
    note: 'Твой на\xA0все 365',
    text: 'С умным домом от\xA0МТС можно по-новому управлять бытовыми процессами: настраивать сценарии через приложение, управлять безопасностью с\xA0помощью камер и\xA0умных датчиков, и\xA0просто испытывать восторг от\xA0умных девайсов.',
    squarePicture: '../../assets/images/products/prods05.svg',
    backgroundImage: '',
    theme: null,
  },
  {
    title: 'MWS MWS MWS MWS MWS MWS MWS MWS MWS MWS MWS MWS MWS MWS MWS MWS MWS MWS MWS MWS MWS MWS MWS MWS MWS',
    subtitle: 'Для водителей',
    note: 'Твой на\xA0все 365',
    text: 'Новые привычки за\xA0рулем – вместо кучи лишних проводов – мультимедийное устройство. Бесшовная синхронизация с\xA0телефоном, проекционный head up дисплей и\xA0облачный 4К видеорегистратор.',
    squarePicture: '../../assets/images/products/prods06.svg',
    backgroundImage: '',
    theme: null,
  },
  {
    title: 'МТС AI МТС AI МТС AI МТС AI МТС AI МТС AI МТС AI МТС AI МТС AI МТС AI МТС AI МТС AI МТС AI МТС AI МТС AI МТС AI',
    subtitle: 'Планирование путешествий',
    note: 'Твой на\xA0все 365',
    text: 'Бронирование отелей, билетов и экскурсий, помощь в\xA0организации досуга в\xA0путешествии – поиск местных гидов, организация нестандартных маршрутов, рекомендации по\xA0культурным местам, барам и\xA0ресторанам',
    squarePicture: '../../assets/images/products/prods07.svg',
    backgroundImage: '',
    theme: null,
  },
  {
    title: 'Маркетолог Маркетолог Маркетолог Маркетолог Маркетолог Маркетолог Маркетолог Маркетолог Маркетолог Маркетолог',
    subtitle: 'Финансовые инструменты',
    note: 'Твой на\xA0все 365',
    text: 'Широкий набор финансовых инструментов, который помогает легко и\xA0эффективно управлять своими финансами и\xA0получать максимум выгоды и\xA0удобства',
    squarePicture: '../../assets/images/products/prods08.svg',
    backgroundImage: '',
    theme: null,
  },
  {
    title: 'IoT IoT IoT IoT IoT IoT IoT IoT IoT IoT IoT IoT IoT IoT IoT IoT IoT IoT IoT IoT IoT IoT IoT IoT',
    subtitle: 'Копи и\xA0трать',
    note: 'Твой на\xA0все 365',
    text: 'Копилка баллов за пользование любыми сервисами МТС и\xA0возможность тратить их на\xA0сервисы внутри экосистемы: на\xA0покупку техники, билетов через сервис МТС live или аренду самокатов Urent',
    squarePicture: '../../assets/images/products/prods11.svg',
    backgroundImage: '',
    theme: null,
  },
  // {
  //   title: 'MTS ID MTS ID MTS ID MTS ID MTS ID MTS ID MTS ID MTS ID MTS ID MTS ID MTS ID MTS ID MTS ID MTS ID MTS ID MTS ID ',
  //   subtitle: 'Единый вход',
  //   note: 'Твой на\xA0все 365',
  //   text: 'Удобный вход во\xA0все сервисы МТС с\xA0единой учетной записью через номер телефона',
  //   squarePicture: '../../assets/images/products/prods12.svg',
  //   backgroundImage: '',
  //   theme: null,
  // },
  // {
  //   title: 'MTS PAY MTS PAY MTS PAY MTS PAY MTS PAY MTS PAY MTS PAY MTS PAY MTS PAY MTS PAY MTS PAY MTS PAY MTS PAY MTS PAY MTS PAY MTS PAY ',
  //   subtitle: 'Бесконтактная оплата',
  //   note: 'Твой на\xA0все 365',
  //   text: 'Простой способ оплаты через имеющиеся технологии в\xA0смартфоне–NFC, QR-код, faceID или покупки с\xA0баланса телефона. Досупен для\xA0клиентов любых банков и абонентов всех операторов',
  //   squarePicture: '../../assets/images/products/prods12.svg',
  //   backgroundImage: '',
  //   theme: null,
  // },
  // {
  //   title: 'YOUTH YOUTH YOUTH',
  //   subtitle: 'Новое поколение',
  //   note: 'Твой на\xA0все 365',
  //   text: 'Продукты и\xA0сервисы экосистемы МТС, адаптированные под потребности поколения Z',
  //   squarePicture: '../../assets/images/products/prods12.svg',
  //   backgroundImage: '',
  //   theme: null,
  // },
];

export const STRATEGY_SLIDER_ITEMS: Slide[] = [
  {
    title: 'customer — ',
    text: 'Наша стратегия нацелена на\xA0построение устойчивого цифрового экосистемного бизнеса на\xA0прочном фундаменте телекоммуникационного лидера',
    backgroundImage: '../../assets/images/strategy/strategy-bg1.jpg',
    subtitle: 'Максимизируем ценность от\xA0клиента',
  },
  {
    title: 'Стратегия — ',
    text: 'Нацелена на\xA0построение устойчивого цифрового экосистемного бизнеса на\xA0прочном фундаменте телекоммуникационного лидера',
    backgroundImage: '../../assets/images/strategy/strategy-bg1.jpg',
    subtitle: 'customer lifetime value 2.0',
  },
  {
    title: 'customer — ',
    text: 'Нацелена на\xA0построение устойчивого цифрового экосистемного бизнеса на\xA0прочном фундаменте телекоммуникационного лидера.',
    backgroundImage: '../../assets/images/strategy/strategy-bg2.jpg',
    subtitle: 'клиент',
  },
  {
    title: 'lifetime — ',
    text: 'Стремимся максимально продлить Время жизни клиента (Lifetime), создавая и\xA0укрепляя эмоциональную привязанность к бренду, повышая степень удовлетворенности и\xA0уровень лояльности клиента',
    backgroundImage: '../../assets/images/strategy/strategy-bg3.jpg',
    subtitle: 'Время жизни клиента',
  },
  {
    title: 'value — ',
    text: 'Фокусируемся на\xA0предложении большей Ценности (Value) клиенту',
    backgroundImage: '../../assets/images/strategy/strategy-bg4.jpg',
    subtitle: 'Ценность',
  },
  {
    title: 'Customer — ',
    text: 'Наша стратегия нацелена на\xA0построение устойчивого цифрового экосистемного бизнеса на\xA0прочном фундаменте телекоммуникационного лидера',
    backgroundImage: '../../assets/images/strategy/strategy-bg1.jpg',
    subtitle: 'максимизируем ценность от\xA0клиента',
  },
];

export const NUMBERS_SLIDER_ITEMS: Slide[] = [
  {
    title: '86m',
    note: 'Абонентов услуг мобильной связи',
    backgroundImage: '../../assets/images/numbers/rec434.png',
    text: '',
    subtitle: '',
    squarePicture: '',
    theme: null,
  },
  {
    title: '17m',
    note: 'Пользователей телефонии, интернета и\xA0ТВ',
    backgroundImage: '../../assets/images/numbers/rec435.jpg',
    text: '',
    subtitle: '',
    squarePicture: '',
    theme: null,
    position: 'bottom',
  },
  {
    title: '80m',
    note: 'Абонентов мобильной связи в\xA0России',
    backgroundImage: '../../assets/images/numbers/rec436.png',
    text: '',
    subtitle: '',
    squarePicture: '',
    theme: null,
  },
  {
    title: '8,8m',
    note: 'Экосистемных клиентов',
    backgroundImage: '../../assets/images/numbers/rec444.jpg',
    text: '',
    subtitle: '',
    squarePicture: 'transform: translate(150px, 340px)',
    theme: null,
    position: 'bottom',
  },
  {
    title: '2,9m',
    note: 'пользователей платной подписки МТС Premium',
    backgroundImage: '../../assets/images/numbers/rec616.jpg',
    text: '',
    subtitle: '',
    squarePicture: '',
    theme: null,
  },
  {
    title: '26m',
    note: 'ежемесячных активных пользователей приложения «Мой МТС»',
    backgroundImage: '../../assets/images/numbers/rec445.jpg',
    text: '',
    subtitle: '',
    squarePicture: 'width:127px; height:181px; transform: translate(32px, 96px)',
    theme: null,
    position: 'bottom',
  },
  {
    title: 'лидер',
    note: 'на\xA0рынке решений для\xA0корпоративных клиентов',
    backgroundImage: '../../assets/images/numbers/rec437.png',
    text: '',
    subtitle: '*по данным исследования агентства «ТМТ Консалтинг»',
    squarePicture: '',
    theme: null,
  },
];

export const CONTACTS_LIST_ITEMS: Link[] = [
  {
    title: 'Партнерам',
    link: '#',
  },
  {
    title: 'Поставщикам',
    link: '#',
  },
  {
    title: 'Госзаказчикам',
    link: '#',
  },
  {
    title: 'Соискателям',
    link: '#',
  },
  {
    title: 'Контакты',
    link: '#',
  },
];

export const PRESS_RELEASE_SLIDER_ITEMS: Link[] = [
  {
    title: 'Руководителем розничной сети МТС назначен Андрей Губанов',
    text: 'Москва, РФ — ПАО «МТС» (MOEX: MTSS), ведущая российская компания по\xA0предоставлению цифровых, медийных и\xA0телекоммуникационных сервисов, объявляет о\xA0назначении генеральным директором розничной сети МТС (АО «РТК») Андрея Губанова. Назначение вступает в\xA0силу с\xA01 января 2023 года.',
    link: '#',
  },
  {
    title: 'Аналитика МТС Travel: средняя стоимость проживания в\xA0российских отелях за\xA0год выросла на\xA010%',
    text: 'another text',
    link: '#',
  },
  {
    title: 'Виртуальная рыбка Джуно от\xA0МТС расскажет о\xA0жизни морских обитателей в\xA0Москвариуме',
    text: 'some another description',
    link: '#',
  },
  {
    title: 'Руководителем розничной сети МТС назначен Андрей Губанов',
    text: 'Москва, РФ — ПАО «МТС» (MOEX: MTSS), ведущая российская компания по\xA0предоставлению цифровых, медийных и\xA0телекоммуникационных сервисов, объявляет о\xA0назначении генеральным директором розничной сети МТС (АО «РТК») Андрея Губанова. Назначение вступает в\xA0силу с\xA01 января 2023 года.',
    link: '#',
  },
  {
    title: 'Аналитика МТС Travel: средняя стоимость проживания в\xA0российских отелях за\xA0год выросла на\xA010%',
    text: 'another text',
    link: '#',
  },
  {
    title: 'Виртуальная рыбка Джуно от\xA0МТС расскажет о\xA0жизни морских обитателей в\xA0Москвариуме',
    text: 'some another description',
    link: '#',
  },
];

export const REPORTS_SLIDER_ITEMS: Link[] = [
  {
    title: 'Годовой отчет',
    picture: '../../assets/images/reports/reportsbg1321316523.jpg',
    link: '#',
  },
  {
    title: 'Отчет устойчивого развития',
    picture: '../../assets/images/reports/reportsbg1321316523.jpg',
    link: '#',
  },
  {
    title: 'Финансовая отчетность',
    picture: '../../assets/images/reports/reportsbg1321316523.jpg',
    link: '#',
  },
  {
    title: 'Документы ПАО "МТС"',
    picture: '../../assets/images/reports/reportsbg1321316523.jpg',
    link: '#',
  },
];

export const INVESTMENT_LIST_ITEMS: Link[] = [
  {
    title: 'Общее собрание акционеров',
    picture: '../../assets/images/reports/reports01.svg',
    link: '#',
  },
  {
    title: 'Прекращение программы АДР',
    picture: '../../assets/images/reports/reports02.svg',
    link: '#',
  },
  {
    title: 'Личный кабинет акционера',
    picture: '../../assets/images/reports/reports03.svg',
    link: '#',
  },
  {
    title: 'Дивиденды',
    picture: '../../assets/images/reports/reports04.svg',
    link: '#',
  },
  {
    title: 'Существенные факты',
    picture: '../../assets/images/reports/reports05.svg',
    link: '#',
  },
  {
    title: 'Раскрытие',
    picture: '../../assets/images/reports/reports06.svg',
    link: '#',
  },
  {
    title: 'Акции и\xA0облигации',
    picture: '../../assets/images/reports/reports07.svg',
    link: '#',
  },
];

export const SOCIETY_SLIDER_ITEMS: SocietySlide[] = [
  {
    title: 'ESG — стратегия ответственного ведения бизнеса',
    subtitle: '',
    note_item_one: 'Снижение уровня негативного воздействия на\xA0окружающую среду',
    note_item_two: 'Организация экологической безопасности',
    note_item_three: 'Соблюдение природоохранного законодательства РФ',
    note_item_four: 'Совершенствование системы экологического менеджмента МТС',
    note_item_five: '',
    note_item_six: '',
    note_item_seven: '',
  },
  {
    title: 'заботимся об окружающей среде',
    subtitle: '',
    note_item_one: 'Снижение уровня негативного воздействия на\xA0окружающую среду',
    note_item_two: 'Организация экологической безопасности',
    note_item_three: 'Соблюдение природоохранного законодательства РФ',
    note_item_four: 'Совершенствование системы экологического менеджмента МТС',
    note_item_five: '',
    note_item_six: '',
    note_item_seven: '',
  },
  {
    title: 'ответственны за\xA0влияние компании на\xA0среду и\xA0общество',
    subtitle: '',
    note_item_one: 'Содействие росту экономики и\xA0благосостояния общества',
    note_item_two: 'Информационная открытость',
    note_item_three: 'Ответственность перед государством',
    note_item_four: 'Равные возможности',
    note_item_five: '',
    note_item_six: '',
    note_item_seven: '',
  },
  {
    title: 'следуем стратегии добросовестного ведения бизнеса',
    subtitle: '',
    note_item_one: 'Кодекс делового поведения и\xA0этики',
    note_item_two: 'Соблюдение законодательства и\xA0высокие этические стандарты',
    note_item_three: 'Поддержание комплаенс системы в\xA0актуальном состоянии',
    note_item_four: 'Незамедлительный ответ на\xA0любые риски и\xA0вызовы',
    note_item_five: '',
    note_item_six: '',
    note_item_seven: '',
  },
];

export const MENU_ITEMS: MenuItem[] = [
  {
    name: 'О МТС',
    link: '#',
    active: true,
    items: [
      {
        title: 'МТС в\xA0Москве и\xA0Московской области',
        link: '#',
      },
      {
        title: 'МТС в\xA0России и\xA0в\xA0мире',
        link: '#',
      },
      {
        title: 'Контакты',
        link: '#',
      },
    ],
  },
  {
    name: 'МЕДИА-ЦЕНТР',
    link: '#',
    items: [
      {
        title: 'Пункт 1',
        link: '#',
      },
      {
        title: 'Пункт 2',
        link: '#',
      },
      {
        title: 'Пункт 3',
        link: '#',
      },
    ],
  },
  {
    name: 'ИНВЕСТОРАМ',
    link: '#',
    items: [
      {
        title: 'Что-то про инвесторов',
        link: '#',
      },
      {
        title: 'Что-то на\xA0инвесторском',
        link: '#',
      },
    ],
  },
  {
    name: 'УСТОЙЧИВОЕ РАЗВИТИЕ',
    link: '#',
    items: [
      {
        title: 'Всего один пункт',
        link: '#',
      },
    ],
  },
  {
    name: 'КОМПЛАЕНС',
    link: '#',
    items: null,
  },
];

export const MENU_BAR_ITEMS: Link[] = [
  {
    title: 'Наша миссия',
    link: 'mission',
  },
  {
    title: 'Продукты',
    link: 'products',
  },
  {
    title: 'Стратегия',
    link: 'strategy',
  },
  {
    title: 'Цифры',
    link: 'numbers',
  },
  {
    title: 'Пресс-релизы',
    link: 'pressrelease',
  },
  {
    title: 'Инвесторам',
    link: 'investors',
  },
  {
    title: 'Обществу',
    link: 'society',
  },
  {
    title: 'Карьера',
    link: 'career',
  },
  {
    title: 'Контакты',
    link: 'contacts',
  },
];

export const FIRST_SCENE_FRAMES_FOR_START = [
  './assets/sequention/clear.webp',
  './assets/sequention/scene-1/0000.webp',
  './assets/sequention/scene-1/0001.webp',
  './assets/sequention/scene-1/0002.webp',
  './assets/sequention/scene-1/0003.webp',
  './assets/sequention/scene-1/0004.webp',
  './assets/sequention/scene-1/0005.webp',
  './assets/sequention/scene-1/0006.webp',
  './assets/sequention/scene-1/0007.webp',
  './assets/sequention/scene-1/0008.webp',
  './assets/sequention/scene-1/0009.webp',
  './assets/sequention/scene-1/0010.webp',
  './assets/sequention/scene-1/0011.webp',
  './assets/sequention/scene-1/0012.webp',
  './assets/sequention/scene-1/0013.webp',
  './assets/sequention/scene-1/0014.webp',
  './assets/sequention/scene-1/0015.webp',
  './assets/sequention/scene-1/0016.webp',
  './assets/sequention/scene-1/0017.webp',
  './assets/sequention/scene-1/0018.webp',
  './assets/sequention/scene-1/0019.webp',
  './assets/sequention/scene-1/0020.webp',
  './assets/sequention/scene-1/0021.webp',
  './assets/sequention/scene-1/0022.webp',
  './assets/sequention/scene-1/0023.webp',
  './assets/sequention/scene-1/0024.webp',
  './assets/sequention/scene-1/0025.webp',
  './assets/sequention/scene-1/0026.webp',
  './assets/sequention/scene-1/0027.webp',
  './assets/sequention/scene-1/0028.webp',
  './assets/sequention/scene-1/0029.webp',
  './assets/sequention/scene-1/0030.webp',
  './assets/sequention/scene-1/0031.webp',
  './assets/sequention/scene-1/0032.webp',
  './assets/sequention/scene-1/0033.webp',
  './assets/sequention/scene-1/0034.webp',
  './assets/sequention/scene-1/0035.webp',
  './assets/sequention/scene-1/0036.webp',
  './assets/sequention/scene-1/0037.webp',
  './assets/sequention/scene-1/0038.webp',
  './assets/sequention/scene-1/0039.webp',
  './assets/sequention/scene-1/0040.webp',
  './assets/sequention/scene-1/0041.webp',
  './assets/sequention/scene-1/0042.webp',
  './assets/sequention/scene-1/0043.webp',
  './assets/sequention/scene-1/0044.webp',
  './assets/sequention/scene-1/0045.webp',
  './assets/sequention/scene-1/0046.webp',
  './assets/sequention/scene-1/0047.webp',
  './assets/sequention/scene-1/0048.webp',
  './assets/sequention/scene-1/0049.webp',
  './assets/sequention/scene-1/0050.webp',
  './assets/sequention/scene-1/0051.webp',
  './assets/sequention/scene-1/0052.webp',
  './assets/sequention/scene-1/0053.webp',
  './assets/sequention/scene-1/0054.webp',
  './assets/sequention/scene-1/0055.webp',
  './assets/sequention/scene-1/0056.webp',
  './assets/sequention/scene-1/0057.webp',
  './assets/sequention/scene-1/0058.webp',
  './assets/sequention/scene-1/0059.webp',
  './assets/sequention/scene-1/0060.webp',
];

export const FIRST_SCENE_FRAMES_FOR_MOVEMENT = [
  './assets/sequention/scene-1/0090.webp',
  './assets/sequention/scene-1/0091.webp',
  './assets/sequention/scene-1/0092.webp',
  './assets/sequention/scene-1/0093.webp',
  './assets/sequention/scene-1/0094.webp',
  './assets/sequention/scene-1/0095.webp',
  './assets/sequention/scene-1/0096.webp',
  './assets/sequention/scene-1/0097.webp',
  './assets/sequention/scene-1/0098.webp',
  './assets/sequention/scene-1/0099.webp',
  './assets/sequention/scene-1/0100.webp',
  './assets/sequention/scene-1/0101.webp',
  './assets/sequention/scene-1/0102.webp',
  './assets/sequention/scene-1/0103.webp',
  './assets/sequention/scene-1/0104.webp',
  './assets/sequention/scene-1/0105.webp',
  './assets/sequention/scene-1/0106.webp',
  './assets/sequention/scene-1/0107.webp',
  './assets/sequention/scene-1/0108.webp',
  './assets/sequention/scene-1/0109.webp',
  './assets/sequention/scene-1/0110.webp',
  './assets/sequention/scene-1/0111.webp',
  './assets/sequention/scene-1/0112.webp',
  './assets/sequention/scene-1/0113.webp',
  './assets/sequention/scene-1/0114.webp',
  './assets/sequention/scene-1/0115.webp',
  './assets/sequention/scene-1/0116.webp',
  './assets/sequention/scene-1/0117.webp',
  './assets/sequention/scene-1/0118.webp',
  './assets/sequention/scene-1/0119.webp',
  './assets/sequention/scene-1/0120.webp',
  './assets/sequention/scene-1/0121.webp',
  './assets/sequention/scene-1/0122.webp',
  './assets/sequention/scene-1/0123.webp',
  './assets/sequention/scene-1/0124.webp',
  './assets/sequention/scene-1/0125.webp',
  './assets/sequention/scene-1/0126.webp',
  './assets/sequention/scene-1/0127.webp',
  './assets/sequention/scene-1/0128.webp',
  './assets/sequention/scene-1/0129.webp',
  './assets/sequention/scene-1/0130.webp',
];

export const SECOND_SCENE_MOVE_1 = [
  './assets/sequention/scene-2/0220.webp',
  './assets/sequention/scene-2/0221.webp',
  './assets/sequention/scene-2/0222.webp',
  './assets/sequention/scene-2/0223.webp',
  './assets/sequention/scene-2/0224.webp',
  './assets/sequention/scene-2/0225.webp',
  './assets/sequention/scene-2/0226.webp',
  './assets/sequention/scene-2/0227.webp',
  './assets/sequention/scene-2/0228.webp',
  './assets/sequention/scene-2/0229.webp',
  './assets/sequention/scene-2/0230.webp',
  './assets/sequention/scene-2/0231.webp',
  './assets/sequention/scene-2/0232.webp',
  './assets/sequention/scene-2/0233.webp',
  './assets/sequention/scene-2/0234.webp',
  './assets/sequention/scene-2/0235.webp',
  './assets/sequention/scene-2/0236.webp',
  './assets/sequention/scene-2/0237.webp',
  './assets/sequention/scene-2/0238.webp',
  './assets/sequention/scene-2/0239.webp',
  './assets/sequention/scene-2/0240.webp',
  './assets/sequention/scene-2/0241.webp',
  './assets/sequention/scene-2/0242.webp',
  './assets/sequention/scene-2/0243.webp',
  './assets/sequention/scene-2/0244.webp',
  './assets/sequention/scene-2/0245.webp',
  './assets/sequention/scene-2/0246.webp',
  './assets/sequention/scene-2/0247.webp',
  './assets/sequention/scene-2/0248.webp',
  './assets/sequention/scene-2/0249.webp',
  './assets/sequention/scene-2/0250.webp',
  './assets/sequention/scene-2/0251.webp',
  './assets/sequention/scene-2/0252.webp',
  './assets/sequention/scene-2/0253.webp',
  './assets/sequention/scene-2/0254.webp',
  './assets/sequention/scene-2/0255.webp',
  './assets/sequention/scene-2/0256.webp',
  './assets/sequention/scene-2/0257.webp',
  './assets/sequention/scene-2/0258.webp',
  './assets/sequention/scene-2/0259.webp',
];
export const SECOND_SCENE_MOVE_2 = [
  './assets/sequention/scene-2/0271.webp',
  './assets/sequention/scene-2/0272.webp',
  './assets/sequention/scene-2/0273.webp',
  './assets/sequention/scene-2/0274.webp',
  './assets/sequention/scene-2/0275.webp',
  './assets/sequention/scene-2/0276.webp',
  './assets/sequention/scene-2/0277.webp',
  './assets/sequention/scene-2/0278.webp',
  './assets/sequention/scene-2/0279.webp',
  './assets/sequention/scene-2/0280.webp',
  './assets/sequention/scene-2/0281.webp',
  './assets/sequention/scene-2/0282.webp',
  './assets/sequention/scene-2/0283.webp',
  './assets/sequention/scene-2/0284.webp',
  './assets/sequention/scene-2/0285.webp',
  './assets/sequention/scene-2/0286.webp',
  './assets/sequention/scene-2/0287.webp',
  './assets/sequention/scene-2/0288.webp',
  './assets/sequention/scene-2/0289.webp',
  './assets/sequention/scene-2/0290.webp',
  './assets/sequention/scene-2/0291.webp',
  './assets/sequention/scene-2/0292.webp',
  './assets/sequention/scene-2/0293.webp',
  './assets/sequention/scene-2/0294.webp',
  './assets/sequention/scene-2/0295.webp',
  './assets/sequention/scene-2/0296.webp',
  './assets/sequention/scene-2/0297.webp',
  './assets/sequention/scene-2/0298.webp',
  './assets/sequention/scene-2/0299.webp',
  './assets/sequention/scene-2/0300.webp',
  './assets/sequention/scene-2/0301.webp',
  './assets/sequention/scene-2/0302.webp',
  './assets/sequention/scene-2/0303.webp',
  './assets/sequention/scene-2/0304.webp',
  './assets/sequention/scene-2/0305.webp',
  './assets/sequention/scene-2/0306.webp',
  './assets/sequention/scene-2/0307.webp',
  './assets/sequention/scene-2/0308.webp',
  './assets/sequention/scene-2/0309.webp',
  './assets/sequention/scene-2/0310.webp',
];
export const SECOND_SCENE_MOVE_3 = [
  './assets/sequention/scene-2/0320.webp',
  './assets/sequention/scene-2/0321.webp',
  './assets/sequention/scene-2/0322.webp',
  './assets/sequention/scene-2/0323.webp',
  './assets/sequention/scene-2/0324.webp',
  './assets/sequention/scene-2/0325.webp',
  './assets/sequention/scene-2/0326.webp',
  './assets/sequention/scene-2/0327.webp',
  './assets/sequention/scene-2/0328.webp',
  './assets/sequention/scene-2/0329.webp',
  './assets/sequention/scene-2/0330.webp',
  './assets/sequention/scene-2/0331.webp',
  './assets/sequention/scene-2/0332.webp',
  './assets/sequention/scene-2/0333.webp',
  './assets/sequention/scene-2/0334.webp',
  './assets/sequention/scene-2/0335.webp',
  './assets/sequention/scene-2/0336.webp',
  './assets/sequention/scene-2/0337.webp',
  './assets/sequention/scene-2/0338.webp',
  './assets/sequention/scene-2/0339.webp',
  './assets/sequention/scene-2/0340.webp',
  './assets/sequention/scene-2/0341.webp',
  './assets/sequention/scene-2/0342.webp',
  './assets/sequention/scene-2/0343.webp',
  './assets/sequention/scene-2/0344.webp',
  './assets/sequention/scene-2/0345.webp',
  './assets/sequention/scene-2/0346.webp',
  './assets/sequention/scene-2/0347.webp',
  './assets/sequention/scene-2/0348.webp',
  './assets/sequention/scene-2/0349.webp',
  './assets/sequention/scene-2/0350.webp',
  './assets/sequention/scene-2/0351.webp',
  './assets/sequention/scene-2/0352.webp',
  './assets/sequention/scene-2/0353.webp',
  './assets/sequention/scene-2/0354.webp',
  './assets/sequention/scene-2/0355.webp',
  './assets/sequention/scene-2/0356.webp',
  './assets/sequention/scene-2/0357.webp',
  './assets/sequention/scene-2/0358.webp',
  './assets/sequention/scene-2/0359.webp',
  './assets/sequention/scene-2/0360.webp',
];
export const SECOND_SCENE_MOVE_4 = [
  './assets/sequention/scene-2/0370.webp',
  './assets/sequention/scene-2/0371.webp',
  './assets/sequention/scene-2/0372.webp',
  './assets/sequention/scene-2/0373.webp',
  './assets/sequention/scene-2/0374.webp',
  './assets/sequention/scene-2/0375.webp',
  './assets/sequention/scene-2/0376.webp',
  './assets/sequention/scene-2/0377.webp',
  './assets/sequention/scene-2/0378.webp',
  './assets/sequention/scene-2/0379.webp',
  './assets/sequention/scene-2/0380.webp',
  './assets/sequention/scene-2/0381.webp',
  './assets/sequention/scene-2/0382.webp',
  './assets/sequention/scene-2/0383.webp',
  './assets/sequention/scene-2/0384.webp',
  './assets/sequention/scene-2/0385.webp',
  './assets/sequention/scene-2/0386.webp',
  './assets/sequention/scene-2/0387.webp',
  './assets/sequention/scene-2/0388.webp',
  './assets/sequention/scene-2/0389.webp',
  './assets/sequention/scene-2/0390.webp',
  './assets/sequention/scene-2/0391.webp',
  './assets/sequention/scene-2/0392.webp',
  './assets/sequention/scene-2/0393.webp',
  './assets/sequention/scene-2/0394.webp',
  './assets/sequention/scene-2/0395.webp',
  './assets/sequention/scene-2/0396.webp',
  './assets/sequention/scene-2/0397.webp',
  './assets/sequention/scene-2/0398.webp',
  './assets/sequention/scene-2/0399.webp',
  './assets/sequention/scene-2/0400.webp',
  './assets/sequention/scene-2/0401.webp',
  './assets/sequention/scene-2/0402.webp',
  './assets/sequention/scene-2/0403.webp',
  './assets/sequention/scene-2/0404.webp',
  './assets/sequention/scene-2/0405.webp',
  './assets/sequention/scene-2/0406.webp',
  './assets/sequention/scene-2/0407.webp',
  './assets/sequention/scene-2/0408.webp',
  './assets/sequention/scene-2/0409.webp',
  './assets/sequention/scene-2/0410.webp',
];
export const SECOND_SCENE_MOVE_5 = [
  './assets/sequention/scene-2/0420.webp',
  './assets/sequention/scene-2/0421.webp',
  './assets/sequention/scene-2/0422.webp',
  './assets/sequention/scene-2/0423.webp',
  './assets/sequention/scene-2/0424.webp',
  './assets/sequention/scene-2/0425.webp',
  './assets/sequention/scene-2/0426.webp',
  './assets/sequention/scene-2/0427.webp',
  './assets/sequention/scene-2/0428.webp',
  './assets/sequention/scene-2/0429.webp',
  './assets/sequention/scene-2/0430.webp',
  './assets/sequention/scene-2/0431.webp',
  './assets/sequention/scene-2/0432.webp',
  './assets/sequention/scene-2/0433.webp',
  './assets/sequention/scene-2/0434.webp',
  './assets/sequention/scene-2/0435.webp',
  './assets/sequention/scene-2/0436.webp',
  './assets/sequention/scene-2/0437.webp',
  './assets/sequention/scene-2/0438.webp',
  './assets/sequention/scene-2/0439.webp',
  './assets/sequention/scene-2/0440.webp',
  './assets/sequention/scene-2/0441.webp',
  './assets/sequention/scene-2/0442.webp',
  './assets/sequention/scene-2/0443.webp',
  './assets/sequention/scene-2/0444.webp',
  './assets/sequention/scene-2/0445.webp',
  './assets/sequention/scene-2/0446.webp',
  './assets/sequention/scene-2/0447.webp',
  './assets/sequention/scene-2/0448.webp',
  './assets/sequention/scene-2/0449.webp',
  './assets/sequention/scene-2/0450.webp',
  './assets/sequention/scene-2/0451.webp',
  './assets/sequention/scene-2/0452.webp',
  './assets/sequention/scene-2/0453.webp',
  './assets/sequention/scene-2/0454.webp',
  './assets/sequention/scene-2/0455.webp',
  './assets/sequention/scene-2/0456.webp',
  './assets/sequention/scene-2/0457.webp',
  './assets/sequention/scene-2/0458.webp',
  './assets/sequention/scene-2/0459.webp',
  './assets/sequention/scene-2/0460.webp',
];
export const SECOND_SCENE_MOVE_6 = [
  './assets/sequention/scene-2/0470.webp',
  './assets/sequention/scene-2/0471.webp',
  './assets/sequention/scene-2/0472.webp',
  './assets/sequention/scene-2/0473.webp',
  './assets/sequention/scene-2/0474.webp',
  './assets/sequention/scene-2/0475.webp',
  './assets/sequention/scene-2/0476.webp',
  './assets/sequention/scene-2/0477.webp',
  './assets/sequention/scene-2/0478.webp',
  './assets/sequention/scene-2/0479.webp',
  './assets/sequention/scene-2/0480.webp',
  './assets/sequention/scene-2/0481.webp',
  './assets/sequention/scene-2/0482.webp',
  './assets/sequention/scene-2/0483.webp',
  './assets/sequention/scene-2/0484.webp',
  './assets/sequention/scene-2/0485.webp',
  './assets/sequention/scene-2/0486.webp',
  './assets/sequention/scene-2/0487.webp',
  './assets/sequention/scene-2/0488.webp',
  './assets/sequention/scene-2/0489.webp',
  './assets/sequention/scene-2/0490.webp',
  './assets/sequention/scene-2/0491.webp',
  './assets/sequention/scene-2/0492.webp',
  './assets/sequention/scene-2/0493.webp',
  './assets/sequention/scene-2/0494.webp',
  './assets/sequention/scene-2/0495.webp',
  './assets/sequention/scene-2/0496.webp',
  './assets/sequention/scene-2/0497.webp',
  './assets/sequention/scene-2/0498.webp',
  './assets/sequention/scene-2/0499.webp',
  './assets/sequention/scene-2/0500.webp',
  './assets/sequention/scene-2/0501.webp',
  './assets/sequention/scene-2/0502.webp',
  './assets/sequention/scene-2/0503.webp',
  './assets/sequention/scene-2/0504.webp',
  './assets/sequention/scene-2/0505.webp',
  './assets/sequention/scene-2/0506.webp',
  './assets/sequention/scene-2/0507.webp',
  './assets/sequention/scene-2/0508.webp',
  './assets/sequention/scene-2/0509.webp',
  './assets/sequention/scene-2/0510.webp',
];
export const SECOND_SCENE_MOVE_7 = [
  './assets/sequention/scene-2/0520.webp',
  './assets/sequention/scene-2/0521.webp',
  './assets/sequention/scene-2/0522.webp',
  './assets/sequention/scene-2/0523.webp',
  './assets/sequention/scene-2/0524.webp',
  './assets/sequention/scene-2/0525.webp',
  './assets/sequention/scene-2/0526.webp',
  './assets/sequention/scene-2/0527.webp',
  './assets/sequention/scene-2/0528.webp',
  './assets/sequention/scene-2/0529.webp',
  './assets/sequention/scene-2/0530.webp',
  './assets/sequention/scene-2/0531.webp',
  './assets/sequention/scene-2/0532.webp',
  './assets/sequention/scene-2/0533.webp',
  './assets/sequention/scene-2/0534.webp',
  './assets/sequention/scene-2/0535.webp',
  './assets/sequention/scene-2/0536.webp',
  './assets/sequention/scene-2/0537.webp',
  './assets/sequention/scene-2/0538.webp',
  './assets/sequention/scene-2/0539.webp',
  './assets/sequention/scene-2/0540.webp',
  './assets/sequention/scene-2/0541.webp',
  './assets/sequention/scene-2/0542.webp',
  './assets/sequention/scene-2/0543.webp',
  './assets/sequention/scene-2/0544.webp',
  './assets/sequention/scene-2/0545.webp',
  './assets/sequention/scene-2/0546.webp',
  './assets/sequention/scene-2/0547.webp',
  './assets/sequention/scene-2/0548.webp',
  './assets/sequention/scene-2/0549.webp',
  './assets/sequention/scene-2/0550.webp',
  './assets/sequention/scene-2/0551.webp',
  './assets/sequention/scene-2/0552.webp',
  './assets/sequention/scene-2/0553.webp',
  './assets/sequention/scene-2/0554.webp',
  './assets/sequention/scene-2/0555.webp',
  './assets/sequention/scene-2/0556.webp',
  './assets/sequention/scene-2/0557.webp',
  './assets/sequention/scene-2/0558.webp',
  './assets/sequention/scene-2/0559.webp',
  './assets/sequention/scene-2/0560.webp',
];
export const SECOND_SCENE_MOVE_8 = [
  './assets/sequention/scene-2/0570.webp',
  './assets/sequention/scene-2/0571.webp',
  './assets/sequention/scene-2/0572.webp',
  './assets/sequention/scene-2/0573.webp',
  './assets/sequention/scene-2/0574.webp',
  './assets/sequention/scene-2/0575.webp',
  './assets/sequention/scene-2/0576.webp',
  './assets/sequention/scene-2/0577.webp',
  './assets/sequention/scene-2/0578.webp',
  './assets/sequention/scene-2/0579.webp',
  './assets/sequention/scene-2/0580.webp',
  './assets/sequention/scene-2/0581.webp',
  './assets/sequention/scene-2/0582.webp',
  './assets/sequention/scene-2/0583.webp',
  './assets/sequention/scene-2/0584.webp',
  './assets/sequention/scene-2/0585.webp',
  './assets/sequention/scene-2/0586.webp',
  './assets/sequention/scene-2/0587.webp',
  './assets/sequention/scene-2/0588.webp',
  './assets/sequention/scene-2/0589.webp',
  './assets/sequention/scene-2/0590.webp',
  './assets/sequention/scene-2/0591.webp',
  './assets/sequention/scene-2/0592.webp',
  './assets/sequention/scene-2/0593.webp',
  './assets/sequention/scene-2/0594.webp',
  './assets/sequention/scene-2/0595.webp',
  './assets/sequention/scene-2/0596.webp',
  './assets/sequention/scene-2/0597.webp',
  './assets/sequention/scene-2/0598.webp',
  './assets/sequention/scene-2/0599.webp',
  './assets/sequention/scene-2/0600.webp',
  './assets/sequention/scene-2/0601.webp',
  './assets/sequention/scene-2/0602.webp',
  './assets/sequention/scene-2/0603.webp',
  './assets/sequention/scene-2/0604.webp',
  './assets/sequention/scene-2/0605.webp',
  './assets/sequention/scene-2/0606.webp',
  './assets/sequention/scene-2/0607.webp',
  './assets/sequention/scene-2/0608.webp',
  './assets/sequention/scene-2/0609.webp',
  './assets/sequention/scene-2/0610.webp',
];
export const SECOND_SCENE_MOVE_9 = [
  './assets/sequention/scene-2/0620.webp',
  './assets/sequention/scene-2/0621.webp',
  './assets/sequention/scene-2/0622.webp',
  './assets/sequention/scene-2/0623.webp',
  './assets/sequention/scene-2/0624.webp',
  './assets/sequention/scene-2/0625.webp',
  './assets/sequention/scene-2/0626.webp',
  './assets/sequention/scene-2/0627.webp',
  './assets/sequention/scene-2/0628.webp',
  './assets/sequention/scene-2/0629.webp',
  './assets/sequention/scene-2/0630.webp',
  './assets/sequention/scene-2/0631.webp',
  './assets/sequention/scene-2/0632.webp',
  './assets/sequention/scene-2/0633.webp',
  './assets/sequention/scene-2/0634.webp',
  './assets/sequention/scene-2/0635.webp',
  './assets/sequention/scene-2/0636.webp',
  './assets/sequention/scene-2/0637.webp',
  './assets/sequention/scene-2/0638.webp',
  './assets/sequention/scene-2/0639.webp',
  './assets/sequention/scene-2/0640.webp',
  './assets/sequention/scene-2/0641.webp',
  './assets/sequention/scene-2/0642.webp',
  './assets/sequention/scene-2/0643.webp',
  './assets/sequention/scene-2/0644.webp',
  './assets/sequention/scene-2/0645.webp',
  './assets/sequention/scene-2/0646.webp',
  './assets/sequention/scene-2/0647.webp',
  './assets/sequention/scene-2/0648.webp',
  './assets/sequention/scene-2/0649.webp',
  './assets/sequention/scene-2/0650.webp',
  './assets/sequention/scene-2/0651.webp',
  './assets/sequention/scene-2/0652.webp',
  './assets/sequention/scene-2/0653.webp',
  './assets/sequention/scene-2/0654.webp',
  './assets/sequention/scene-2/0655.webp',
  './assets/sequention/scene-2/0656.webp',
  './assets/sequention/scene-2/0657.webp',
  './assets/sequention/scene-2/0658.webp',
  './assets/sequention/scene-2/0659.webp',
  './assets/sequention/scene-2/0660.webp',
];
export const SECOND_SCENE_MOVE_10 = [
  './assets/sequention/scene-2/0670.webp',
  './assets/sequention/scene-2/0671.webp',
  './assets/sequention/scene-2/0672.webp',
  './assets/sequention/scene-2/0673.webp',
  './assets/sequention/scene-2/0674.webp',
  './assets/sequention/scene-2/0675.webp',
  './assets/sequention/scene-2/0676.webp',
  './assets/sequention/scene-2/0677.webp',
  './assets/sequention/scene-2/0678.webp',
  './assets/sequention/scene-2/0679.webp',
  './assets/sequention/scene-2/0680.webp',
  './assets/sequention/scene-2/0681.webp',
  './assets/sequention/scene-2/0682.webp',
  './assets/sequention/scene-2/0683.webp',
  './assets/sequention/scene-2/0684.webp',
  './assets/sequention/scene-2/0685.webp',
  './assets/sequention/scene-2/0686.webp',
  './assets/sequention/scene-2/0687.webp',
  './assets/sequention/scene-2/0688.webp',
  './assets/sequention/scene-2/0689.webp',
  './assets/sequention/scene-2/0690.webp',
  './assets/sequention/scene-2/0691.webp',
  './assets/sequention/scene-2/0692.webp',
  './assets/sequention/scene-2/0693.webp',
  './assets/sequention/scene-2/0694.webp',
  './assets/sequention/scene-2/0695.webp',
  './assets/sequention/scene-2/0696.webp',
  './assets/sequention/scene-2/0697.webp',
  './assets/sequention/scene-2/0698.webp',
  './assets/sequention/scene-2/0699.webp',
  './assets/sequention/scene-2/0700.webp',
  './assets/sequention/scene-2/0701.webp',
  './assets/sequention/scene-2/0702.webp',
  './assets/sequention/scene-2/0703.webp',
  './assets/sequention/scene-2/0704.webp',
  './assets/sequention/scene-2/0705.webp',
  './assets/sequention/scene-2/0706.webp',
  './assets/sequention/scene-2/0707.webp',
  './assets/sequention/scene-2/0708.webp',
  './assets/sequention/scene-2/0709.webp',
  './assets/sequention/scene-2/0710.webp',
];
export const SECOND_SCENE_MOVE_11 = [
  './assets/sequention/scene-2/0720.webp',
  './assets/sequention/scene-2/0721.webp',
  './assets/sequention/scene-2/0722.webp',
  './assets/sequention/scene-2/0723.webp',
  './assets/sequention/scene-2/0724.webp',
  './assets/sequention/scene-2/0725.webp',
  './assets/sequention/scene-2/0726.webp',
  './assets/sequention/scene-2/0727.webp',
  './assets/sequention/scene-2/0728.webp',
  './assets/sequention/scene-2/0729.webp',
  './assets/sequention/scene-2/0730.webp',
  './assets/sequention/scene-2/0731.webp',
  './assets/sequention/scene-2/0732.webp',
  './assets/sequention/scene-2/0733.webp',
  './assets/sequention/scene-2/0734.webp',
  './assets/sequention/scene-2/0735.webp',
  './assets/sequention/scene-2/0736.webp',
  './assets/sequention/scene-2/0737.webp',
  './assets/sequention/scene-2/0738.webp',
  './assets/sequention/scene-2/0739.webp',
  './assets/sequention/scene-2/0740.webp',
  './assets/sequention/scene-2/0741.webp',
  './assets/sequention/scene-2/0742.webp',
  './assets/sequention/scene-2/0743.webp',
  './assets/sequention/scene-2/0744.webp',
  './assets/sequention/scene-2/0745.webp',
  './assets/sequention/scene-2/0746.webp',
  './assets/sequention/scene-2/0747.webp',
  './assets/sequention/scene-2/0748.webp',
  './assets/sequention/scene-2/0749.webp',
  './assets/sequention/scene-2/0750.webp',
  './assets/sequention/scene-2/0751.webp',
  './assets/sequention/scene-2/0752.webp',
  './assets/sequention/scene-2/0753.webp',
  './assets/sequention/scene-2/0754.webp',
  './assets/sequention/scene-2/0755.webp',
  './assets/sequention/scene-2/0756.webp',
  './assets/sequention/scene-2/0757.webp',
  './assets/sequention/scene-2/0758.webp',
  './assets/sequention/scene-2/0759.webp',
  './assets/sequention/scene-2/0760.webp',
];
